"""Add purchase_id to serial_numbers

Revision ID: 493cfcf8622f
Revises: a8474a2c3260
Create Date: 2025-10-01 00:54:36.813448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493cfcf8622f'
down_revision = 'a8474a2c3260'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial_numbers', sa.Column('purchase_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_serial_numbers_purchase_id'), 'serial_numbers', ['purchase_id'], unique=False)
    op.create_foreign_key(None, 'serial_numbers', 'purchases', ['purchase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serial_numbers', type_='foreignkey')
    op.drop_index(op.f('ix_serial_numbers_purchase_id'), table_name='serial_numbers')
    op.drop_column('serial_numbers', 'purchase_id')
    # ### end Alembic commands ### 