"""Add purchase_id to journal_entries

Revision ID: a8474a2c3260
Revises: d46631b271ba
Create Date: 2025-10-01 00:25:24.125830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8474a2c3260'
down_revision = 'd46631b271ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backups_backup_type'), table_name='backups')
    op.drop_index(op.f('ix_backups_created_at'), table_name='backups')
    op.drop_index(op.f('ix_backups_created_by'), table_name='backups')
    op.drop_index(op.f('ix_backups_status'), table_name='backups')
    op.drop_table('backups')
    op.drop_table('asset_maintenance')
    op.drop_table('asset_images')
    op.drop_table('asset_category_configs')
    op.drop_table('asset_depreciation')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_backup_schedules_backup_type'), table_name='backup_schedules')
    op.drop_index(op.f('ix_backup_schedules_created_by'), table_name='backup_schedules')
    op.drop_index(op.f('ix_backup_schedules_frequency'), table_name='backup_schedules')
    op.drop_index(op.f('ix_backup_schedules_is_active'), table_name='backup_schedules')
    op.drop_table('backup_schedules')
    op.alter_column('app_settings', 'company_logo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('app_settings', 'invoice_line_height',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('1.4'))
    op.add_column('cogs_entries', sa.Column('cost', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('cogs_entries', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('cogs_entries', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('cogs_entries', sa.Column('branch_id', sa.String(), nullable=True))
    op.add_column('cogs_entries', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('cogs_entries', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('cogs_entries', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('cogs_entries', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cogs_entries', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('cogs_entries', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_index(op.f('ix_cogs_entries_id'), table_name='cogs_entries')
    op.create_foreign_key(None, 'cogs_entries', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'cogs_entries', 'branches', ['branch_id'], ['id'])
    op.drop_column('cogs_entries', 'description')
    op.drop_column('cogs_entries', 'reference')
    op.drop_column('cogs_entries', 'unit_cost')
    op.drop_column('cogs_entries', 'total_cost')
    op.drop_column('cogs_entries', 'is_adjusted')
    op.alter_column('inventory_transactions', 'serial_numbers',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.add_column('journal_entries', sa.Column('purchase_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_journal_entries_purchase_id'), 'journal_entries', ['purchase_id'], unique=False)
    op.create_foreign_key(None, 'journal_entries', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'journal_entries', 'purchases', ['purchase_id'], ['id'])
    op.drop_index(op.f('idx_permissions_action'), table_name='permissions')
    op.drop_index(op.f('idx_permissions_module'), table_name='permissions')
    op.drop_index(op.f('idx_permissions_name'), table_name='permissions')
    op.alter_column('products', 'unit_of_measure_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('purchase_items', sa.Column('is_inventory', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'purchase_items', 'accounting_codes', ['asset_accounting_code_id'], ['id'])
    op.create_foreign_key(None, 'purchase_items', 'accounting_codes', ['asset_accum_depr_account_code_id'], ['id'])
    op.add_column('purchases', sa.Column('bank_account_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'bank_accounts', ['bank_account_id'], ['id'])
    op.alter_column('role_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('role_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('role_permissions_role_id_permission_id_key'), 'role_permissions', type_='unique')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'])
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sale_items', 'serial_numbers',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('suppliers', 'contact_info')
    op.drop_index(op.f('idx_user_audit_logs_action'), table_name='user_audit_logs')
    op.drop_index(op.f('idx_user_audit_logs_created_at'), table_name='user_audit_logs')
    op.drop_index(op.f('idx_user_audit_logs_module'), table_name='user_audit_logs')
    op.drop_index(op.f('idx_user_audit_logs_user_id'), table_name='user_audit_logs')
    op.drop_index(op.f('idx_users_role_id'), table_name='users')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'pin_hash')
    op.add_column('vat_payments', sa.Column('bank_account_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'vat_payments', 'bank_accounts', ['bank_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vat_payments', type_='foreignkey')
    op.drop_column('vat_payments', 'bank_account_id')
    op.add_column('users', sa.Column('pin_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('idx_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('idx_user_audit_logs_user_id'), 'user_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_audit_logs_module'), 'user_audit_logs', ['module'], unique=False)
    op.create_index(op.f('idx_user_audit_logs_created_at'), 'user_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_user_audit_logs_action'), 'user_audit_logs', ['action'], unique=False)
    op.add_column('suppliers', sa.Column('contact_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sale_items', 'serial_numbers',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('role_permissions_role_id_permission_id_key'), 'role_permissions', ['role_id', 'permission_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('role_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('role_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'bank_account_id')
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_column('purchase_items', 'is_inventory')
    op.alter_column('products', 'unit_of_measure_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('idx_permissions_name'), 'permissions', ['name'], unique=False)
    op.create_index(op.f('idx_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_index(op.f('idx_permissions_action'), 'permissions', ['action'], unique=False)
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.drop_index(op.f('ix_journal_entries_purchase_id'), table_name='journal_entries')
    op.drop_column('journal_entries', 'purchase_id')
    op.alter_column('inventory_transactions', 'serial_numbers',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.add_column('cogs_entries', sa.Column('is_adjusted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('cogs_entries', sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cogs_entries', sa.Column('unit_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cogs_entries', sa.Column('reference', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cogs_entries', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cogs_entries', type_='foreignkey')
    op.drop_constraint(None, 'cogs_entries', type_='foreignkey')
    op.create_index(op.f('ix_cogs_entries_id'), 'cogs_entries', ['id'], unique=False)
    op.alter_column('cogs_entries', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('cogs_entries', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cogs_entries', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cogs_entries', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('cogs_entries', 'updated_at')
    op.drop_column('cogs_entries', 'created_at')
    op.drop_column('cogs_entries', 'branch_id')
    op.drop_column('cogs_entries', 'created_by')
    op.drop_column('cogs_entries', 'notes')
    op.drop_column('cogs_entries', 'cost')
    op.alter_column('app_settings', 'invoice_line_height',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True,
               existing_server_default=sa.text('1.4'))
    op.alter_column('app_settings', 'company_logo_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('backup_schedules',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('backup_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('include_files', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_run', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_run', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('backup_schedules_pkey'))
    )
    op.create_index(op.f('ix_backup_schedules_is_active'), 'backup_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_backup_schedules_frequency'), 'backup_schedules', ['frequency'], unique=False)
    op.create_index(op.f('ix_backup_schedules_created_by'), 'backup_schedules', ['created_by'], unique=False)
    op.create_index(op.f('ix_backup_schedules_backup_type'), 'backup_schedules', ['backup_type'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('VEHICLE', 'EQUIPMENT', 'FURNITURE', 'BUILDING', 'LAND', 'SOFTWARE', 'INTANGIBLE', 'MACHINERY', 'COMPUTER', 'OFFICE_EQUIPMENT', 'OTHER', 'inventory', 'INVENTORY', name='assetcategory'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'SOLD', 'DISPOSED', 'UNDER_MAINTENANCE', 'LOST', 'STOLEN', name='assetstatus'), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('assigned_department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('branch_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('purchase_cost', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('salvage_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('accumulated_depreciation', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('depreciation_method', postgresql.ENUM('STRAIGHT_LINE', 'DECLINING_BALANCE', 'SUM_OF_YEARS', 'UNITS_OF_PRODUCTION', 'NONE', name='depreciationmethod'), autoincrement=False, nullable=True),
    sa.Column('useful_life_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('depreciation_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('model_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('warranty_expiry', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('vehicle_registration', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('engine_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('chassis_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vehicle_make', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vehicle_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vehicle_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fuel_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transmission_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_service_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('next_service_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('insurance_expiry', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('license_expiry', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('accounting_code_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('warranty_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('maintenance_schedule', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('inventory_item_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('inventory_quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['accounting_code_id'], ['accounting_codes.id'], name='assets_accounting_code_id_fkey'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name='assets_assigned_to_fkey'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='assets_branch_id_fkey'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['products.id'], name='assets_inventory_item_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='assets_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=False)
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_table('asset_depreciation',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('depreciation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('depreciation_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('accumulated_depreciation', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('book_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('journal_entry_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_depreciation_asset_id_fkey')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['accounting_entries.id'], name=op.f('asset_depreciation_journal_entry_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_depreciation_pkey'))
    )
    op.create_table('asset_category_configs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('VEHICLE', 'EQUIPMENT', 'FURNITURE', 'BUILDING', 'LAND', 'SOFTWARE', 'INTANGIBLE', 'MACHINERY', 'COMPUTER', 'OFFICE_EQUIPMENT', 'OTHER', 'inventory', 'INVENTORY', name='assetcategory'), autoincrement=False, nullable=False),
    sa.Column('default_depreciation_method', postgresql.ENUM('STRAIGHT_LINE', 'DECLINING_BALANCE', 'SUM_OF_YEARS', 'UNITS_OF_PRODUCTION', 'NONE', name='depreciationmethod'), autoincrement=False, nullable=True),
    sa.Column('default_useful_life_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('default_depreciation_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('default_salvage_value_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('custom_fields_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('maintenance_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('maintenance_interval_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_category_configs_pkey')),
    sa.UniqueConstraint('category', name=op.f('asset_category_configs_category_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('asset_images',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('image_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_images_asset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_images_pkey'))
    )
    op.create_table('asset_maintenance',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('maintenance_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('maintenance_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('next_maintenance_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('service_provider', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('service_provider_contact', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('parts_replaced', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('work_performed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('technician_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_maintenance_asset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_maintenance_pkey'))
    )
    op.create_table('backups',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('backup_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('backups_pkey'))
    )
    op.create_index(op.f('ix_backups_status'), 'backups', ['status'], unique=False)
    op.create_index(op.f('ix_backups_created_by'), 'backups', ['created_by'], unique=False)
    op.create_index(op.f('ix_backups_created_at'), 'backups', ['created_at'], unique=False)
    op.create_index(op.f('ix_backups_backup_type'), 'backups', ['backup_type'], unique=False)
    # ### end Alembic commands ### 