import os
from typing import Optional
from pydantic_settings import BaseSettings, SettingsConfigDict
from pydantic import Field


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
    )

    # Default fallback updated to standard port 5432
    database_url: str = Field("postgresql://cassidymugadza:casmic@127.0.0.1:5432/cnperpdimensions")

    # Security
    secret_key: str = Field("test-secret-key-for-development-only")
    algorithm: str = Field("HS256")
    access_token_expire_minutes: int = Field(30)

    # Redis
    redis_url: str = Field("redis://localhost:6379")

    # Application
    app_name: str = Field("CNPERP")
    debug: bool = Field(True)
    environment: str = Field("development")

    # Email
    smtp_host: Optional[str] = Field(None)
    smtp_port: int = Field(587)
    smtp_user: Optional[str] = Field(None)
    smtp_password: Optional[str] = Field(None)

    # File Storage
    upload_dir: str = Field("uploads")
    max_file_size: int = Field(10485760)  # 10MB

    # VAT Settings (Botswana)
    default_vat_rate: float = Field(14.0)
    default_currency: str = Field("BWP")

    # Pagination
    default_page_size: int = Field(20)
    max_page_size: int = Field(100)

    # Branding / Reporting
    brand_logo_path: str = Field("app/static/branding/logo.png")
    brand_watermark_text: str = Field("CNP ERP")
    brand_header_text: str = Field("CNP ERP - Confidential")
    brand_footer_text: str = Field("Generated by CNP ERP")

    # Generic Report Export Constraints
    generic_report_max_flat_rows: int = Field(5000)
    generic_report_max_bytes: int = Field(2_000_000)  # ~2MB raw JSON
    generic_report_cache_ttl_seconds: int = Field(600)
    generic_report_allowed_meta_keys: str = Field("title,period,data")  # comma-separated

    # Inventory posting configuration: 'immediate' or 'received'
    inventory_posting_mode: str = Field("immediate")


settings = Settings()
